### ISSUE TITLE
Missing method .read

### ISSUE THREAD

**Issue by dignifiedquire** [pull-stream/pull-stream-to-stream#1]
Regular readable node streams have `.read([size])` method to directly read from the stream. This is currently missing from the stream exposed.

Ref: https://nodejs.org/docs/latest/api/stream.html#stream_readable_read_size

**Comment by dignifiedquire** [comment]
It's worth noting that this method would be only useful if the `readable` event is correctly emitted.

**Comment by dominictarr** [comment]
you don't need that if you use the stream by piping another stream to it, which is the best way to use streams anyway. I'd recommend considering these legacy apis. 
I recently wrote a blog post on the history of streams which might be helpful context here: http://dominictarr.com/post/145135293917/history-of-streams

**Comment by dignifiedquire** [comment]
Thanks, the problem is that I specifically do not want to use `.pipe` as it breaks the rest of the code. What I'm trying to do is similar to the pull-handshake where I have multiple messages that are length prefixed in the beginning and want to pipe the rest of the stream somewhere else. But if I use a `.pipe` instead of `.read` I'm not able to stop reading after x bytes (at least I haven't found a way where I don't loose some bytes in between).

My workaround was to use `.unshift` when I read too much, that's why there is #2. Any ideas on how to solve this with pipe?

**Comment by dominictarr** [comment]
Can you link me to the code you are working on?

I suggest avoiding ever taking a stream as an argument and then modifying it,
instead return a stream - make the stream be the module. The best thing about this is that then your protocol is independent of transport.

So, you could make a stream that only processes a fixed number of bytes,
then pipe the input to it. you could use pull-handshake and then convert that to a node stream,

if you really want to use node streams though, you wouldn't go wrong by studying @mafintosh's code,
prehaps: https://github.com/mafintosh/hypercore-protocol

**Comment by dignifiedquire** [comment]
Thanks @dominictarr I just use pull-streams for everything and am much happier now :)
